name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black ruff mypy isort pytest
      - name: Auto-format (black)
        run: black .
      - name: Lint (ruff)
        run: ruff check . --fix
      - name: Type check (mypy)
        run: mypy .
      - name: Tests
        run: pytest -q
